databases:
  # 1. The PostgreSQL Database
  - name: linkflow-db
    plan: free
    postgresMajorVersion: "15"

services:
  # 2. The FastAPI Backend
  - type: web
    name: linkflow-backend
    env: python
    plan: free
    buildCommand: "cd Backend && pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: '3.11.0'
      - key: DATABASE_URL
        fromDatabase:
          name: linkflow-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://link-flow-9et0iw32f-payalbsd2004-7135s-projects.vercel.app", "https://link-flow-1496-nzhrxeclc-payalbsd2004-7135s-projects.vercel.app", "https://linkflow-app-pruijgoek-payalbsd2004-7135s-projects.vercel.app", "https://linkflow-app.vercel.app"]'
      - key: GOOGLE_CLIENT_ID
        value: '78361509176-jthrqsmcuohr1drp20bjs6rqt0kbahj0.apps.googleusercontent.com'
